# HARBOR OIDC CONFIGURATION
# Configure Harbor container registry with Authentik OIDC authentication
# This runs via tofu-controller after Harbor is deployed
# Reference: docs/HARBOR_SSO_AUTOMATION.md

# Provider versions are centralized in root terraform.tf
# Note: kubernetes provider uses in-cluster config (no explicit provider block needed)

# Data source: Harbor admin password (Vault SSOT → ESO → K8s secret)
# Password generated by terraform/02-services/harbor-admin-password.tf
# Synced from Vault by ExternalSecret to harbor/harbor-admin-initial
data "kubernetes_secret" "harbor_admin_password" {
  metadata {
    name      = "harbor-admin-initial"
    namespace = "harbor"
  }
}

provider "harbor" {
  url      = var.harbor_url
  username = "admin"
  password = data.kubernetes_secret.harbor_admin_password.data["HARBOR_ADMIN_PASSWORD"]
}

# Harbor OIDC credentials come from main.tf vault_kv_secret_v2.harbor_oidc resource
# Reference the resource directly instead of using data source (avoids plan-time dependency)
# The resource is created in main.tf and we need it to exist before configuring Harbor

# Configure Harbor OIDC authentication with Authentik
resource "harbor_config_auth" "oidc" {
  # Set authentication mode to OIDC
  auth_mode = "oidc_auth"

  # OIDC provider configuration
  oidc_name          = "Authentik"
  oidc_endpoint      = "${var.authentik_url}/application/o/harbor/"
  oidc_client_id     = jsondecode(vault_kv_secret_v2.harbor_oidc.data_json)["client_id"]
  oidc_client_secret = jsondecode(vault_kv_secret_v2.harbor_oidc.data_json)["client_secret"]
  oidc_scope         = "openid,email,profile"
  oidc_verify_cert   = true

  # Auto-create users on first OIDC login
  oidc_auto_onboard = true

  # Username claim from OIDC token
  oidc_user_claim = "preferred_username"

  # Group mapping configuration
  oidc_groups_claim = "groups"
  oidc_admin_group  = "harbor-admins"
}
