"""Tests for automatic example generation from critic_scopes_expected_to_recall data.

Examples are now auto-generated by a database VIEW that combines file_sets
and whole-snapshot entries. These tests verify the VIEW produces correct examples.
"""

from __future__ import annotations

import pytest_bazel

from props.core.ids import SnapshotSlug
from props.core.models.examples import ExampleKind, SingleFileSetExample, WholeSnapshotExample
from props.core.splits import Split
from props.db.examples import Example
from props.db.models import Snapshot
from props.db.session import get_session


def test_generate_examples_train_split(synced_test_db):
    """Test example VIEW for TRAIN split creates per-file-set examples + whole-snapshot."""
    with get_session() as session:
        # Use test-trivial fixture (train split)
        slug = SnapshotSlug("test-fixtures/train1")
        snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert snapshot.split == Split.TRAIN

        # Query examples from VIEW
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # Should have multiple examples (one per unique file set + full-specimen)
        assert len(examples) > 1

        # Each example should be an Example ORM object
        for example in examples:
            assert isinstance(example, Example)

            # Check example_kind is valid
            assert isinstance(example.example_kind, ExampleKind)
            assert example.example_kind in [ExampleKind.WHOLE_SNAPSHOT, ExampleKind.FILE_SET]

            # Verify example_spec conversion works
            example_spec = example.to_example_spec()
            assert isinstance(example_spec, WholeSnapshotExample | SingleFileSetExample)

            if example.example_kind == ExampleKind.WHOLE_SNAPSHOT:
                # Whole snapshot examples
                assert example.files_hash is None
                assert isinstance(example_spec, WholeSnapshotExample)
            else:
                # Single file set examples
                assert example.example_kind == ExampleKind.FILE_SET
                assert example.files_hash is not None
                assert isinstance(example_spec, SingleFileSetExample)
                assert example_spec.files_hash == example.files_hash

        # One example should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in examples)
        assert full_specimen_found, "Whole-snapshot example not found in generated examples"


def test_generate_examples_valid_test_split(synced_test_db):
    """Test example VIEW for VALID split (per-file + whole-snapshot) and TEST split (whole-snapshot only)."""
    with get_session() as session:
        # Test VALID split using test-validation fixture
        slug = SnapshotSlug("test-fixtures/valid1")
        valid_snapshot = session.query(Snapshot).filter_by(slug=slug).one()
        assert valid_snapshot.split == Split.VALID

        # Query examples from VIEW
        valid_examples = session.query(Example).filter_by(snapshot_slug=slug).all()

        # VALID should have multiple examples (per-file + whole-snapshot)
        assert len(valid_examples) > 1, "VALID split should generate per-file examples for targeted mode"

        # At least one should be whole-snapshot
        full_specimen_found = any(ex.example_kind == ExampleKind.WHOLE_SNAPSHOT for ex in valid_examples)
        assert full_specimen_found, "VALID split should include whole-snapshot example"

        # Note: TEST split testing skipped - no test-fixtures/test snapshot in git
        # TEST split behavior is well-defined: only generate full-specimen example


def test_generate_examples_unique_file_sets(synced_test_db):
    """Test that duplicate file sets are deduplicated by the VIEW using git fixtures."""
    with get_session() as session:
        slug = SnapshotSlug("test-fixtures/train1")

        # test-trivial fixture already has multiple file sets; the view should deduplicate them
        examples = session.query(Example).filter_by(snapshot_slug=slug).all()
        assert examples, "Expected examples for test-trivial fixture"

        file_set_examples = [ex for ex in examples if ex.example_kind == ExampleKind.FILE_SET]
        whole_snapshot_examples = [ex for ex in examples if ex.example_kind == ExampleKind.WHOLE_SNAPSHOT]

        assert whole_snapshot_examples, "Whole-snapshot example not found"
        assert file_set_examples, "Expected at least one file-set example"

        # Deduplication: file_set_examples should have unique (snapshot_slug, files_hash)
        file_set_keys = {(ex.snapshot_slug, ex.files_hash) for ex in file_set_examples}
        assert len(file_set_keys) == len(file_set_examples), "File-set examples should already be deduplicated"

        # Expect exactly one whole-snapshot row
        assert len(whole_snapshot_examples) == 1, "Expected exactly one whole-snapshot example"

        # Total examples = unique file sets + one whole-snapshot
        assert len(examples) == len(file_set_examples) + 1


if __name__ == "__main__":
    pytest_bazel.main()
