# Composite action for saving Bazel cache
#
# Use after bazel-cache action to save the cache on completion.
# Only saves if the cache wasn't restored (cache miss) and skip_cache is false.
#
# Usage:
#   - uses: ./.github/actions/bazel-cache-save
#     if: always()
#     with:
#       cache-hit: ${{ steps.bazel-cache.outputs.cache-hit }}
#       cache-key: ${{ steps.bazel-cache.outputs.cache-key }}
#       skip_cache: ${{ steps.buildbuddy.outputs.enabled }}
name: Bazel Cache Save
description: Save Bazel cache (use after bazel-cache action)

inputs:
  cache-hit:
    description: "Whether cache was restored (from bazel-cache output)"
    required: true
  cache-key:
    description: "Cache key to save under (from bazel-cache output)"
    required: true
  skip_cache:
    description: "Skip saving cache (e.g., when using BuildBuddy remote cache)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Save Bazel cache
      if: inputs.cache-hit != 'true' && inputs.skip_cache != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ inputs.cache-key }}
