# Collects all files in bazel-testlogs directory (including undeclared outputs) as an artifact.
name: Collect Test Logs
description: Collect and upload all Bazel test logs

inputs:
  artifact-name:
    description: "Name for the uploaded artifact (will have -$run_id appended)"
    required: false
    default: "test-logs"
  retention-days:
    description: "Number of days to retain the artifact"
    required: false
    default: "14"

runs:
  using: composite
  steps:
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}-${{ github.run_id }}
        path: bazel-testlogs/
        if-no-files-found: ignore
        retention-days: ${{ inputs.retention-days }}
