name: "Setup Nix"
description: "Install Nix for cluster tool installation"

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v17

    - name: Configure Nix PATH
      shell: bash
      run: |
        # Add Nix profile to PATH for subsequent steps
        echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

    - name: Configure environment
      shell: bash
      run: |
        # Match .envrc: Force Bazel to use system GCC instead of Nix GCC
        # This avoids glibc mismatch issues with rustc and proc-macros
        echo "CC=/usr/bin/gcc" >> $GITHUB_ENV
