"""Module extension for proxy configuration.

This generates a proxy_env.bzl file that can be loaded by BUILD files.
The content differs based on whether we're on Claude Code web (with TLS proxy)
or local development (no proxy needed).

Detection: checks if ~/.cache/bazel-proxy/combined_ca.pem exists.
The session hook creates this file when setting up the TLS-inspecting proxy.
"""

# Fixed paths matching bazel_proxy_setup.py constants
_BAZEL_PROXY_PORT = "18081"
_BAZEL_COMBINED_CA = "/root/.cache/bazel-proxy/combined_ca.pem"

def _proxy_config_repo_impl(repository_ctx):
    """Generate proxy_env.bzl based on proxy file existence."""

    # Detect proxy by checking if the CA bundle exists
    # The session hook creates this file when setting up the proxy
    ca_path = repository_ctx.path(_BAZEL_COMBINED_CA)

    if ca_path.exists:
        # Claude Code web with TLS-inspecting proxy
        local_proxy = "http://localhost:{}".format(_BAZEL_PROXY_PORT)
        content = '''\
# Auto-generated proxy config for Claude Code web
PROXY_ENV = {{
    "HTTPS_PROXY": "{proxy}",
    "HTTP_PROXY": "{proxy}",
    "https_proxy": "{proxy}",
    "http_proxy": "{proxy}",
    "SSL_CERT_FILE": "{ca}",
    "REQUESTS_CA_BUNDLE": "{ca}",
}}
'''.format(proxy = local_proxy, ca = _BAZEL_COMBINED_CA)
    else:
        # Local development - no proxy needed
        content = """# Default proxy config for local development
PROXY_ENV = {}
"""

    repository_ctx.file("proxy_env.bzl", content)
    repository_ctx.file("BUILD.bazel", """\
# Auto-generated by proxy_config module extension
exports_files(["proxy_env.bzl"])
""")

proxy_config_repo = repository_rule(
    implementation = _proxy_config_repo_impl,
    doc = "Repository rule that generates proxy configuration based on file existence.",
)

def _proxy_config_impl(_module_ctx):
    """Module extension implementation."""
    proxy_config_repo(name = "proxy_config")

proxy_config = module_extension(
    implementation = _proxy_config_impl,
    doc = "Module extension for proxy configuration.",
)
