# Composite action for Bazel cache setup and save
#
# Handles:
# - Setting up Bazelisk
# - Deriving cache key from workflow/job name + file hashes
# - Restoring and saving Bazel cache (skipped if using BuildBuddy remote cache)
#
# Usage:
#   - uses: ./.github/actions/bazel-cache
#     id: bazel-cache
#     with:
#       extra_hash: ${{ hashFiles('Cargo.toml', 'Cargo.lock') }}
#       skip_cache: ${{ steps.buildbuddy.outputs.enabled }}
#
#   # ... your build steps ...
#
#   - uses: ./.github/actions/bazel-cache-save
#     with:
#       cache-hit: ${{ steps.bazel-cache.outputs.cache-hit }}
#       cache-key: ${{ steps.bazel-cache.outputs.cache-key }}
name: Bazel Cache Setup
description: Setup Bazelisk and restore Bazel cache with auto-derived keys

inputs:
  extra_hash:
    description: "Additional hash to append to cache key (use hashFiles() at call site)"
    required: false
    default: ""
  skip_cache:
    description: "Skip GitHub Actions cache (e.g., when using BuildBuddy remote cache)"
    required: false
    default: "false"

outputs:
  cache-hit:
    description: "Whether the cache was restored"
    value: ${{ steps.cache-restore.outputs.cache-hit }}
  cache-key:
    description: "The cache key (use this for bazel-cache-save)"
    value: ${{ steps.cache-key.outputs.key }}

runs:
  using: composite
  steps:
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3

    - name: Derive cache key
      id: cache-key
      shell: bash
      env:
        BASE_HASH: ${{ hashFiles('MODULE.bazel', 'requirements_bazel.txt') }}
        EXTRA_HASH: ${{ inputs.extra_hash }}
        WORKFLOW: ${{ github.workflow }}
        JOB: ${{ github.job }}
      run: |
        # Slugify workflow name and job for cache key prefix
        SLUG=$(echo "${WORKFLOW}-${JOB}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')

        # Combine base hash with extra hash if provided
        if [[ -n "$EXTRA_HASH" ]]; then
          HASH="${BASE_HASH:0:8}-${EXTRA_HASH:0:8}"
        else
          HASH="${BASE_HASH:0:16}"
        fi

        KEY="bazel-${SLUG}-${HASH}"
        echo "key=$KEY" >> $GITHUB_OUTPUT
        echo "slug=$SLUG" >> $GITHUB_OUTPUT

    - name: Restore Bazel cache
      id: cache-restore
      if: inputs.skip_cache != 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ steps.cache-key.outputs.key }}
        restore-keys: bazel-${{ steps.cache-key.outputs.slug }}-
