"""Example model and scope-based training example identification.

Examples define training/evaluation scopes (whole-snapshot or file-set).
Primary key: (snapshot_slug, example_kind, COALESCE(files_hash, '')).

Examples are a VIEW (not a table) derived from file_sets + whole-snapshot entries.
See db/migrations for VIEW definition. This ORM model provides read-only access.

This module also provides shared logic for loading training examples across splits
(train/valid/test), which is the single source of truth for GEPA and other optimizers.
"""

from __future__ import annotations

from sqlalchemy import Enum, Integer, String, func
from sqlalchemy.orm import Mapped, Query, Session, mapped_column, relationship

from props.core.ids import SnapshotSlug
from props.core.models.examples import ExampleKind, ExampleSpec, SingleFileSetExample, WholeSnapshotExample
from props.core.splits import Split
from props.db.models import Base, Snapshot, SnapshotSlugColumn

# =============================================================================
# Example Model
# =============================================================================


class Example(Base):
    """Training/evaluation examples - VIEW backed by file_sets + whole-snapshot entries.

    Each example defines a specific scope to evaluate (whole-snapshot or file-set).

    THIS IS A DATABASE VIEW, NOT A TABLE:
    - Whole-snapshot: SELECT slug, 'whole_snapshot', NULL, recall_denominator FROM snapshots
    - File-set: SELECT snapshot_slug, 'file_set', files_hash, recall_denominator
                FROM file_sets GROUP BY snapshot_slug, files_hash

    Read-only access: Query examples, don't insert/update (examples are auto-generated by the VIEW).

    See docs/training_strategy.md for details on example generation.

    recall_denominator: Computed directly from ground truth (true_positives) using
    is_tp_in_expected_recall_scope() in the VIEW definition. This allows correct recall computation
    even when all critic runs fail (0/N) vs when no runs exist (NULL).

    NOTE: recall_denominator is the EXPECTED count - critics CAN find issues outside expected
    scopes (achieving >100% recall). See critic_scopes_expected_to_recall for details.
    """

    __tablename__ = "examples"
    __table_args__ = ()

    # Composite primary key: (snapshot_slug, example_kind, COALESCE(files_hash, ''))
    # No FK constraint needed for VIEWs (underlying tables handle relationships)
    snapshot_slug: Mapped[SnapshotSlug] = mapped_column(SnapshotSlugColumn(), primary_key=True)
    example_kind: Mapped[ExampleKind] = mapped_column(
        Enum(
            ExampleKind,
            name="example_kind_enum",
            create_constraint=False,  # VIEW, enum type already exists
            values_callable=lambda x: [e.value for e in x],  # Use enum value not name
        ),
        primary_key=True,
        comment="Example kind (whole_snapshot or file_set)",
    )
    files_hash: Mapped[str | None] = mapped_column(
        String, primary_key=True, comment="File set hash for file_set examples, NULL for whole_snapshot"
    )

    # Expected recall occurrences computed from ground truth
    recall_denominator: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Number of TP occurrences in expected recall scope for this example (from ground truth)",
    )

    # No timestamps - VIEWs don't support created_at/updated_at

    # Relationships - use string references to avoid circular imports
    # NOTE: examples is a VIEW, so we need explicit primaryjoin (no FK constraint exists)
    snapshot_obj: Mapped[Snapshot] = relationship(
        "Snapshot", primaryjoin="foreign(Example.snapshot_slug) == Snapshot.slug", viewonly=True
    )
    # Note: AgentRun stores snapshot_slug/example_kind/files_hash in JSONB type_config,
    # so there's no direct FK relationship possible. Query AgentRun via type_config filtering instead.

    def to_example_spec(self) -> ExampleSpec:
        """Convert this Example ORM object to an ExampleSpec Pydantic model."""
        if self.example_kind == ExampleKind.WHOLE_SNAPSHOT:
            return WholeSnapshotExample(snapshot_slug=self.snapshot_slug)
        if self.example_kind == ExampleKind.FILE_SET:
            if self.files_hash is None:
                raise ValueError(f"Example {self.snapshot_slug} has example_kind=file_set but files_hash is NULL")
            return SingleFileSetExample(snapshot_slug=self.snapshot_slug, files_hash=self.files_hash)
        raise ValueError(f"Unknown example_kind: {self.example_kind}")

    @classmethod
    def _query_by_spec(cls, session: Session, spec: ExampleSpec) -> Query[Example]:
        """Build query to find Example by ExampleSpec."""
        if isinstance(spec, WholeSnapshotExample):
            return session.query(cls).filter_by(
                snapshot_slug=spec.snapshot_slug, example_kind=ExampleKind.WHOLE_SNAPSHOT, files_hash=None
            )
        return session.query(cls).filter_by(
            snapshot_slug=spec.snapshot_slug, example_kind=ExampleKind.FILE_SET, files_hash=spec.files_hash
        )

    @classmethod
    def from_spec(cls, session: Session, spec: ExampleSpec) -> Example:
        """Look up Example by ExampleSpec. Raises NoResultFound if not found."""
        return cls._query_by_spec(session, spec).one()

    @classmethod
    def from_spec_or_none(cls, session: Session, spec: ExampleSpec) -> Example | None:
        """Look up Example by ExampleSpec. Returns None if not found."""
        return cls._query_by_spec(session, spec).one_or_none()


# =============================================================================
# Training Example Loading (GEPA Integration)
# =============================================================================


def count_available_examples_for_split(session: Session, split: Split) -> int:
    """Count available training examples for a split, matching GEPA's loading logic.

    Args:
        session: SQLAlchemy session
        split: Split to count examples for

    Returns:
        Number of training examples available for this split

    Note:
        Validation/test snapshots should have exactly one example each (full-specimen).
        This count trusts that db sync created the right examples.
    """
    # Count examples efficiently with a join
    count = (
        session.query(func.count(Example.snapshot_slug))
        .join(Snapshot, Snapshot.slug == Example.snapshot_slug)
        .where(Snapshot.split == split)
        .scalar()
    )
    return count or 0


def count_available_examples_by_scope_all(
    session: Session, splits: list[Split]
) -> dict[tuple[Split, ExampleKind], int]:
    """Count examples grouped by split and example kind.

    Args:
        session: SQLAlchemy session
        splits: List of splits to count examples for

    Returns:
        Dict mapping (split, example_kind) to count, ordered by split then example_kind.
    """
    results = (
        session.query(Snapshot.split, Example.example_kind, func.count(Example.snapshot_slug))
        .join(Snapshot, Snapshot.slug == Example.snapshot_slug)
        .where(Snapshot.split.in_(splits))
        .group_by(Snapshot.split, Example.example_kind)
        .order_by(Snapshot.split, Example.example_kind)
        .all()
    )
    # Build ordered dict (Python 3.7+ preserves insertion order)
    return {(split, example_kind): count for split, example_kind, count in results}


def get_examples_for_split(session: Session, split: Split) -> list[Example]:
    """Get all training examples for a split.

    This is the main entrypoint for loading training examples. Returns Example objects
    ready for evaluation by querying the Examples table directly.

    CRITICAL: Dataset Order Determinism
    ------------------------------------
    GEPA's ListDataLoader uses list indices as DataIds (0, 1, 2, ...).
    Examples are ordered by (snapshot_slug, example_kind, files_hash NULLS FIRST) for
    deterministic ordering across all runs, ensuring checkpoint compatibility.

    Args:
        session: SQLAlchemy session
        split: Split to load (TRAIN, VALID, or TEST)

    Returns:
        List of Example objects, ordered deterministically:
        - TRAIN: All examples (per-file + full-specimen for tighter feedback loops)
        - VALID/TEST: Full-specimen examples only (ensured by db sync at example generation time)

        Examples are detached from the session (via expunge) so they can be used
        as value objects outside the session context.

    Note:
        Example filtering (per-file vs full-specimen) is handled at db sync time.
        This function trusts that the Examples table contains the correct examples for each split.
    """
    # Query examples directly with join to filter by split
    # Order by (snapshot_slug, example_kind, files_hash NULLS FIRST) for deterministic ordering
    examples = (
        session.query(Example)
        .join(Snapshot, Snapshot.slug == Example.snapshot_slug)
        .where(Snapshot.split == split)
        .order_by(Example.snapshot_slug, Example.example_kind, Example.files_hash.nullsfirst())
        .all()
    )

    # Detach from session so they can be used as value objects
    for example in examples:
        session.expunge(example)

    return examples


__all__ = [
    "Example",
    "count_available_examples_by_scope_all",
    "count_available_examples_for_split",
    "get_examples_for_split",
]
