# Composite action for BuildBuddy remote cache setup
#
# Configures Bazel to use BuildBuddy as a read/write remote cache
# when BUILDBUDDY_API_KEY is provided. Writes to ~/.config/bazel/buildbuddy.bazelrc
# and ensures ~/.bazelrc has a try-import for it.
#
# Usage:
#   - uses: ./.github/actions/setup-buildbuddy
#     id: buildbuddy
#     with:
#       api_key: ${{ secrets.BUILDBUDDY_API_KEY }}
#
#   # Bazel automatically picks up the config - no extra flags needed
#   - run: bazel build //...
name: Setup BuildBuddy
description: Configure BuildBuddy remote cache for Bazel

inputs:
  api_key:
    description: "BuildBuddy API key (optional - no-op if not provided)"
    required: false
    default: ""

outputs:
  enabled:
    description: "Whether BuildBuddy is configured ('true' or 'false')"
    value: ${{ steps.setup.outputs.enabled }}

runs:
  using: composite
  steps:
    - name: Setup BuildBuddy
      id: setup
      shell: bash
      env:
        BUILDBUDDY_API_KEY: ${{ inputs.api_key }}
      run: |
        if [[ -z "$BUILDBUDDY_API_KEY" ]]; then
          echo "enabled=false" >> $GITHUB_OUTPUT
          echo "BuildBuddy API key not provided, skipping remote cache setup"
          exit 0
        fi

        # Run the shared setup script (writes to ~/.config/bazel/buildbuddy.bazelrc)
        "${{ github.workspace }}/tools/setup-buildbuddy.sh"

        echo "enabled=true" >> $GITHUB_OUTPUT
