# Minimal watchdog.observers stubs used by wt

from watchdog.events import FileSystemEventHandler

class Observer:
    def __init__(self) -> None: ...
    def schedule(self, handler: FileSystemEventHandler, path: str, recursive: bool = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def join(self, timeout: float | None = ...) -> None: ...
